package com.bxy.salestrategies.model;


import java.util.Date;

// Generated 2013-5-4 16:44:24 by Hibernate Tools 4.0.0

/**
 * Activity generated by hbm2java
 */
public class Activity implements java.io.Serializable {

	private Integer id;
	private int crmuserId;
	private Date end_time;
	private Date start_time;
	private String title;
    private int event_type;
    private int status;
    private int activity_coachType;
	public Activity() {
	}

	public Activity(int crmuserId, Date starttime) {
		this.crmuserId = crmuserId;
		this.start_time = starttime;
	}

	public Activity(int crmuserId, Date endtime, Date starttime, String title) {
		this.crmuserId = crmuserId;
		this.end_time = endtime;
		this.start_time = starttime;
		this.title = title;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getCrmuserId() {
		return this.crmuserId;
	}

	public void setCrmuserId(int crmuserId) {
		this.crmuserId = crmuserId;
	}

	
	

	public Date getEnd_time() {
		return end_time;
	}

	public void setEnd_time(Date end_time) {
		this.end_time = end_time;
	}

	public Date getStart_time() {
		return start_time;
	}

	public void setStart_time(Date start_time) {
		this.start_time = start_time;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public int getEvent_type() {
		return event_type;
	}

	public void setEvent_type(int event_type) {
		this.event_type = event_type;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getActivity_coachType() {
		return activity_coachType;
	}

	public void setActivity_coachType(int activity_coachType) {
		this.activity_coachType = activity_coachType;
	}
	
}
